### ISSUE TITLE
more changes for Ventro

### ISSUE THREAD

**Issue by af19** [lemonstand/lscloud-theme-ventro#1]
- [x] Remvove hover on mobile
- [x] Single column mobile nav
- [x] Social icons breaking on product page
- [x] Breadcrumbs too big on mobile
- [x] Animate mobile nav (slide down)
- [x] Theme screenshots for dashboard
- [ ] Change product image depending on colour selected
- [x] Rearrange images and text on product page (tablet)
- [ ] Use fastclick.js to make site feel less laggy on mobile?

@dhalarewich 
@robotpony

**Comment by dhalarewich** [comment]
Some other things I found:
- [x] Attributes are hard coded into product page (materials & details). This should be dynamic, and possibly not show up at all if no attributes are added.
- [x] Need to test product extras, and add styles if needed.
- [x] Quantity field looks too wide. Although, when there is a single product option [it looks pretty good](https://www.dropbox.com/s/mnscy8w1spgs7gk/Screenshot%202015-05-21%2013.53.12.png?dl=0). Possible [example here](http://i2.wp.com/blog.lemonstand.com/wp-content/uploads/2015/04/Screenshot-2015-04-14-21.58.03-e1429074485139.png?resize=880%2C659)
- [x] :hover on product in grid shouldn't hide the price and name from view
- [x] view button displayed on :hover on product in grid should be easier to click. I propose making the clickable area same size as product image.
- [x] "Added to cart" message should be more obvious, and fade away after a few seconds. See Charlotte Hosten website for good example.
- [ ] Consider using a zoom feature on the main product image. Example: https://charlottehosten.com/product/white-pearls-bracelet
- [x] Consider adding Related Products to the product detail page. The section should only be displayed if there are associated Related Products. [Possible example here](http://i2.wp.com/blog.lemonstand.com/wp-content/uploads/2015/04/Screenshot-2015-04-14-21.58.03-e1429074485139.png?resize=880%2C659)
- [x] Link to open the mini cart in the top-right navigation needs an icon I believe. A simple cart line icon would do well. Charlotte Hosten provides an example, and I particularly like that the number of items is colored.
- [x] Search in mobile menu is awkward and needs rejigging
- [x] Theme should support using a logo instead of text in header. This should use a theme customization option, and be tested with logos of different sizes.
- [x] The option comments on product page needs a better placeholder than "Halo?"
- [ ] JS files could use some combining / minify, and replace some with CDN versions.

**Comment by JerkyTreats** [comment]
Looks like the majority of these have been completed, and this issue is stale. Closing.
